# src/main/resources/application.properties
server.port=8080
app.env=dev
wa.phone_number_id=821827761015750
wa.access_token=EAALgD9tJfxgBPzMeJfCtPZAs4y147JN62DrtD1eRhRwTjjsNhWhDIA9iAbbOcpZCIOh6WwI6iAZAT7hRdxmnsMBMhLE0XJE5IMw7JI97yAUeivsCjDFW7y4afQQLJMkCOMpccI26BwOpbAVzTB65bwPSpGdgu9eugvZBPNXsvqR1kZB4Jx3QGagJ3p5tGvC8ZBZA3mn8HGolbQRQheOslzvIdrRjfs3duxpOOxgsyT40WTDihateRr6OQEZALCGCPSwvOdVitzDN7y9kcpxAoRyR6tbcNgZDZD
wa.verify_token=unipoli-verify-token

# Meta (WhatsApp)
meta.verify.token=tu_token_de_verificacion
meta.access.token=EAABxxxxxx

# Google Calendar
google.client.id=XXX.apps.googleusercontent.com
google.client.secret=XXX
google.refresh.token=XXX
google.redirect.uri=https://developers.google.com/oauthplayground
