# src/main/resources/application.properties
server.port=8080
app.env=dev
wa.phone_number_id=821827761015750
wa.access_token=EAALgD9tJfxgBPh4VR36yh3WwLd59KOgY3UEE62md55kRWgZCjevpxcMAH8sOK9JVrBUB35ZA8h1mZBxMTrdWb5wSo7SuZCrCZBC6yeIjeXNIUz3QNz9eICUtfw0ao3QiM2iNiCWkZAdXceObnxBTAZAgNuUorBUz1HMwJmwgzH2XZCEi6VrFfZB91fjb7o58idNLUz3EaAth01ZCMKkwJ6wPB2qC2fL2qWBXYmj1brq2ZBLu8hxcZA0ZD
wa.verify_token=unipoli-verify-token

# Meta (WhatsApp)
meta.verify.token=tu_token_de_verificacion
meta.access.token=EAABxxxxxx

# Google Calendar
google.client.id=XXX.apps.googleusercontent.com
google.client.secret=XXX
google.refresh.token=XXX
google.redirect.uri=https://developers.google.com/oauthplayground
