# src/main/resources/application.properties
server.port=8080
app.env=dev
wa.phone_number_id=821827761015750
wa.access_token=EAALgD9tJfxgBP74uXSIfgwr1UpEoZCQBOdZCrvzKLbKSk5VqchZA3Lrqv0N06EfrgQ0ZBuJ2n0dUdFVgk3WA5gwYgZAZCczPyPTO9J5dvLZCl5vLUI23R1UminbQq8qKZBQFnWh77rI1710JAtYyRR3kH4zi5qjnRiAUUrItKgWXzOESmL98N18lqqsdwJaSIsTfjNTecCPTbojQLFqH72OKCahEdcNlgW56GcuyWVzJgg4h59kZD
wa.verify_token=unipoli-verify-token

# Meta (WhatsApp)
meta.verify.token=tu_token_de_verificacion
meta.access.token=EAABxxxxxx

# GOOGLE OAUTH
google.client.id=325051165792-6guvshaudam9e43s3epou64tt27jo33c.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=https://unluxuriant-uninducted-marlena.ngrok-free.dev/google/oauth/callback

google.timezone=America/Mexico_City

# SCOPES
google.scopes=https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/calendar.events
